version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0.31
    volumes:
      - db-data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###
  php-fpm:
    image: php:8.1.14-fpm-alpine3.16
    volumes:
      - ./:/var/www/budget-tracker-backend
    build: .docker/php-fpm
    working_dir: /var/www/budget-tracker-backend

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./:/var/www/budget-tracker-backend
      - ./.docker/nginx/templates:/etc/nginx/templates/
    build: ./.docker/nginx
    ports:
      - "80:80"

volumes:
  db-data:
